/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.md87.android.activityrecorder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int list=0x7f060001;
        public static final int togglebutton=0x7f060000;
    }
    public static final class layout {
        public static final int item=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class raw {
        public static final int basic_model=0x7f040000;
    }
    public static final class string {
        public static final int activity_dancing=0x7f050009;
        public static final int activity_idle=0x7f05000a;
        public static final int activity_idle_sitting=0x7f05000c;
        public static final int activity_idle_standing=0x7f05000b;
        public static final int activity_unknown=0x7f050004;
        public static final int activity_vehicle=0x7f05000d;
        public static final int activity_vehicle_bus=0x7f05000e;
        public static final int activity_vehicle_car=0x7f05000f;
        public static final int activity_walking=0x7f050005;
        public static final int activity_walking_stairs=0x7f050006;
        public static final int activity_walking_stairs_down=0x7f050008;
        public static final int activity_walking_stairs_up=0x7f050007;
        public static final int app_name=0x7f050000;
        public static final int error_disconnected=0x7f050001;
        public static final int service_disabled=0x7f050003;
        public static final int service_enabled=0x7f050002;
    }
}
