/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.md87.android.sensorlogger;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int countdownblurb=0x7f060002;
        public static final int countdownheader=0x7f060000;
        public static final int countdowntimer=0x7f060001;
        public static final int intro1=0x7f060004;
        public static final int intro2=0x7f060005;
        public static final int intro3=0x7f060006;
        public static final int introheader=0x7f060003;
        public static final int introstart=0x7f060007;
        public static final int recordingblurb=0x7f06000a;
        public static final int recordingcount=0x7f060009;
        public static final int recordingheader=0x7f060008;
        public static final int resultsblurb=0x7f06000c;
        public static final int resultscorrect=0x7f06000e;
        public static final int resultsheader=0x7f06000b;
        public static final int resultsno=0x7f060010;
        public static final int resultsresult=0x7f06000d;
        public static final int resultsyes=0x7f06000f;
        public static final int thanksblurb=0x7f060012;
        public static final int thanksheader=0x7f060011;
        public static final int thankslink=0x7f060014;
        public static final int thankslinktext=0x7f060013;
    }
    public static final class layout {
        public static final int countdown=0x7f030000;
        public static final int intro=0x7f030001;
        public static final int recording=0x7f030002;
        public static final int results=0x7f030003;
        public static final int thanks=0x7f030004;
    }
    public static final class raw {
        public static final int basic_model=0x7f040000;
    }
    public static final class string {
        public static final int activity_dancing=0x7f05001e;
        public static final int activity_idle_sitting=0x7f050020;
        public static final int activity_idle_standing=0x7f05001f;
        public static final int activity_unknown=0x7f05001a;
        public static final int activity_vehicle_bus=0x7f050021;
        public static final int activity_vehicle_car=0x7f050022;
        public static final int activity_walking=0x7f05001b;
        public static final int activity_walking_stairs_down=0x7f05001d;
        public static final int activity_walking_stairs_up=0x7f05001c;
        public static final int analysingheader=0x7f05000b;
        public static final int app_name=0x7f050000;
        public static final int continuebutton=0x7f050005;
        public static final int correct_activity=0x7f050017;
        public static final int correct_button=0x7f050019;
        public static final int correct_title=0x7f050018;
        public static final int countdownblurb=0x7f050008;
        public static final int countdownheader=0x7f050006;
        public static final int countdowninitial=0x7f050007;
        public static final int error_disconnected=0x7f050009;
        public static final int intro1=0x7f050002;
        public static final int intro2=0x7f050003;
        public static final int intro3=0x7f050004;
        public static final int introheader=0x7f050001;
        public static final int nobutton=0x7f050016;
        public static final int recordingheader=0x7f05000a;
        public static final int recordinginitial=0x7f05000c;
        public static final int recordingwait=0x7f05000d;
        public static final int resultsblurb=0x7f05000f;
        public static final int resultscorrect=0x7f050011;
        public static final int resultsheader=0x7f05000e;
        public static final int resultsresult=0x7f050010;
        public static final int thanksblurb=0x7f050013;
        public static final int thanksheader=0x7f050012;
        public static final int thankslinktext=0x7f050014;
        public static final int yesbutton=0x7f050015;
    }
}
