/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.md87.android.contextanalyser.locale;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int frame=0x7f050000;
        public static final int spinner=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int location_name=0x7f040002;
        public static final int plugin_dialog_install=0x7f040004;
        /**  "Install" should match up with the plugin_dialog_install string 
         */
        public static final int plugin_dialog_market_not_available=0x7f040007;
        public static final int plugin_dialog_need_locale_informative=0x7f040006;
        public static final int plugin_dialog_need_locale_message=0x7f040005;
        /**  NOTE: these names cannot be changed without also changing the string constants in com.twofortyfouram.MarketActivity.  You will NOT get a compile time error 
         */
        public static final int plugin_dialog_title=0x7f040003;
        public static final int plugin_name=0x7f040001;
    }
}
