/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.md87.android.contexthome;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blank=0x7f020000;
        public static final int focused_application_background=0x7f020001;
        public static final int grid_selector=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int pressed_application_background=0x7f020004;
    }
    public static final class id {
        public static final int body=0x7f050005;
        public static final int content=0x7f050002;
        public static final int fixedcontent=0x7f050000;
        public static final int image=0x7f050003;
        public static final int score=0x7f050006;
        public static final int scroll=0x7f050001;
        public static final int title=0x7f050004;
    }
    public static final class layout {
        public static final int container=0x7f030000;
        public static final int scroller=0x7f030001;
        public static final int titledimage=0x7f030002;
        public static final int z=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
