/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.md87.android.contextanalyser;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int webview=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int basic_model=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int permdesc_broadcast=0x7f05000e;
        public static final int permdesc_readJourneys=0x7f050008;
        public static final int permdesc_readPlaces=0x7f050004;
        public static final int permdesc_receiveUpdates=0x7f050002;
        public static final int permdesc_writeJourneys=0x7f05000a;
        public static final int permdesc_writePlaces=0x7f050006;
        public static final int permgroupdesc=0x7f05000c;
        public static final int permgrouplabel=0x7f05000b;
        public static final int permlab_broadcast=0x7f05000d;
        public static final int permlab_readJourneys=0x7f050007;
        public static final int permlab_readPlaces=0x7f050003;
        public static final int permlab_receiveUpdates=0x7f050001;
        public static final int permlab_writeJourneys=0x7f050009;
        public static final int permlab_writePlaces=0x7f050005;
    }
}
